<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2020-06-04T20:07:52Z" name="Default suite" finished-at="2020-06-04T20:07:55Z" duration-ms="3360">
    <groups>
    </groups>
    <test started-at="2020-06-04T20:07:52Z" name="Default test" finished-at="2020-06-04T20:07:55Z" duration-ms="3360">
      <class name="com.atmecs.api.testscripts.post.apikey.ipsur.TC_01_Create_New_Register_Ipsum">
        <test-method signature="TC_01_Post_Ipsum_Register()[pri:0, instance:com.atmecs.api.testscripts.post.apikey.ipsur.TC_01_Create_New_Register_Ipsum@55740540]" started-at="2020-06-04T20:07:52Z" name="TC_01_Post_Ipsum_Register" finished-at="2020-06-04T20:07:55Z" duration-ms="3328" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[INFO: Status Code Validation Failed. expected [201] but found [401]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: INFO: Status Code Validation Failed. expected [201] but found [401]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at com.atmecs.api.testscripts.post.apikey.ipsur.TC_01_Create_New_Register_Ipsum.TC_01_Post_Ipsum_Register(TC_01_Create_New_Register_Ipsum.java:47)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_01_Post_Ipsum_Register -->
      </class> <!-- com.atmecs.api.testscripts.post.apikey.ipsur.TC_01_Create_New_Register_Ipsum -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
